<?php

$labels = [];
$labels['filters'] = 'Filtravimas';
$labels['storedfilters'] = 'Išsaugoti filtrai';
$labels['whatfilter'] = 'Filtruoti laukelį';
$labels['searchstring'] = 'Contains';
$labels['movefrom'] = 'Tikrinti katalogą';
$labels['moveto'] = 'Perkelti į';
$labels['from'] = 'From';
$labels['to'] = 'To';
$labels['cc'] = 'CC';
$labels['subject'] = 'Subject';
$labels['delete'] = 'Pašalinti';
$labels['filterpriority'] = 'Nepaisyti kitų filtrų';

$messages = [];
$messages['nosearchstring'] = "Laukas 'Contains' negali būti tuščias.";
$messages['successfullysaved'] = "Filtras išaugotas.";
$messages['unsuccessfullysaved'] = "Klaida: filtras neišsaugotas.";
$messages['successfullydeleted'] = "Filtras pašalintas.";
$messages['unsuccessfullydeleted'] = "Klaida: filtras nepašalintas.";
$messages['msg_if_field'] = 'Jeigu laukelyje';
$messages['msg_contains'] = 'yra';
$messages['msg_move_msg_in'] = 'perkelti žinutę į';
$messages['msg_move_msg_from'] = 'nuo';
$messages['msg_no_stored_filters'] = "Nėra jokių išsaugotų filtrų.";
